# Generated by Django 5.1.2 on 2024-11-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_item_delete_myshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
